# Generated by Django 3.2.2 on 2021-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
