# Generated by Django 3.2.18 on 2023-05-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fcmdevice',
            name='fcm_django__registr_dacdb2_idx',
        ),
    ]
