# Generated by Django 3.2.18 on 2026-04-02 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcm_django", "0011_fcmdevice_fcm_django_registration_id_user_id_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="fcmdevice",
            name="token_updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text=(
                    "Set when the current registration token is first stored "
                    "and whenever it changes."
                ),
                verbose_name="Token update date",
            ),
        ),
    ]
